root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/demo-parser ./cmd/server"
  bin = "./tmp/demo-parser server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "bin", ".git"]
  delay = 500
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
